apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rh-syft
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/rh-syft/rh-syft@sha256:b858e75afc31f43630be4538b27b86a4da79c51a90cf3ff761deb2fd97cda438
        name: container-image
        resources: {}
status: {}
