apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-syft
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-syft
    app.kubernetes.io/part-of: rh-syft
  name: rh-syftznwi
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rh-syft
    weight: 100
status: {}
