apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-syft
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-syft
    app.kubernetes.io/part-of: rh-syft
  name: rh-syft
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rh-syft
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rh-syft
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/rh-syft/rh-syft@sha256:1f071668828c04ff9120b8a454ab070082bd6ab123586fa84c21db9b96f05995
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
status: {}
