apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-syft
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-syft
    app.kubernetes.io/part-of: rh-syft
  name: rh-syft
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: rh-syft
status:
  loadBalancer: {}
